chore: convert 17.0 developer/context
keymanapp/help.keyman.com pull request #1099
Opened 2024-03-06 09:01 UTC by Meng-Heng

context/messages.php
 context/model-editor.php
 context/new-lm-project-parameters.php
 context/new-project-parameters.php
 context/new-project.php
 context/new.php
 context/options.php
 context/project.php
 context/startup.php

2024-03-07 01:57 UTC, darcywong00 commented on developer/17.0/context/messages.md
> +![Message window](/cdn/deploy/img/developer/100/ui/frmMessages.cf604504166eb7147d118b03cb32b576.png)
I think all the referenced images on the PR should go to 
/cdn/dev/img/... instead of /cdn/deploy/img/... because the sha (random string before .png) gets generated

Maybe 19 links to check

2024-03-08 02:52 UTC, darcywong00 commented on developer/17.0/context/messages.md
> +![Message window](/cdn/dev/img/developer/100/ui/frmMessages.cf604504166eb7147d118b03cb32b576.png)
You updated this one to dev. But you'll also need to remove the sha from the filename like this:

```suggestion
![Message window](/cdn/dev/img/developer/100/ui/frmMessages.png)
```

Same for all the images on this PR

2024-03-08 03:33 UTC, Meng-Heng commented on developer/17.0/context/model-editor.md
> +![Model Editor - Details tab](/cdn/dev/img/developer/130/ui/frmModelEditor_Details.ca5e794b04209c60854111b86dffc2eb.png)
```suggestion
![Model Editor - Details tab](/cdn/dev/img/developer/130/ui/frmModelEditor_Details.png)

```

2024-03-08 03:34 UTC, Meng-Heng commented on developer/17.0/context/model-editor.md
> +![Model Editor - Wordlist tab - Design view](/cdn/dev/img/developer/130/ui/frmModelEditor_Wordlist_Design.3d5806a162509669143d8d9076d35435.png)
```suggestion
![Model Editor - Wordlist tab - Design view](/cdn/dev/img/developer/130/ui/frmModelEditor_Wordlist_Design.png)

```

2024-03-08 03:34 UTC, Meng-Heng commented on developer/17.0/context/model-editor.md
> +![Model Editor - Wordlist tab - Code view](/cdn/dev/img/developer/130/ui/frmModelEditor_Wordlist_Code.8949586895480db1efe81e3bf2428c5f.png)
```suggestion
![Model Editor - Wordlist tab - Code view](/cdn/dev/img/developer/130/ui/frmModelEditor_Wordlist_Code.png)

```

2024-03-08 03:34 UTC, Meng-Heng commented on developer/17.0/context/model-editor.md
> +![Model Editor - Source tab](/cdn/dev/img/developer/130/ui/frmModelEditor_Source.a2acf54f09987aec8f01d0e4c3090a53.png)
```suggestion
![Model Editor - Source tab](/cdn/dev/img/developer/130/ui/frmModelEditor_Source.png)

```

2024-03-08 03:34 UTC, Meng-Heng commented on developer/17.0/context/model-editor.md
> +![Model Editor - Build tab](/cdn/dev/img/developer/130/ui/frmModelEditor_Build.ba427b3deb25d34951cf0f7001ea1d8b.png)
```suggestion
![Model Editor - Build tab](/cdn/dev/img/developer/130/ui/frmModelEditor_Build.png)

```

2024-03-08 03:35 UTC, Meng-Heng commented on developer/17.0/context/new-lm-project-parameters.md
> +![New Lexical Model Project Parameters dialog](/cdn/dev/img/developer/120/ui/frmNewLMProjectParameters.9f0c6da7d4898fdaec60bb6a88da84d7.png)
```suggestion
![New Lexical Model Project Parameters dialog](/cdn/dev/img/developer/120/ui/frmNewLMProjectParameters.png)

```

2024-03-08 03:35 UTC, Meng-Heng commented on developer/17.0/context/new-project-parameters.md
> +![New Project Parameters dialog](/cdn/dev/img/developer/120/ui/frmNewProjectParameters.efdd6549232a56ad84ef7571366b5801.png)
```suggestion
![New Project Parameters dialog](/cdn/dev/img/developer/120/ui/frmNewProjectParameters.png)

```

2024-03-08 03:35 UTC, Meng-Heng commented on developer/17.0/context/new-project.md
> +![New Project dialog](/cdn/dev/img/developer/120/ui/frmNewProject.75cfc2a2d8f00b2790937cf3729dddd7.png)
```suggestion
![New Project dialog](/cdn/dev/img/developer/120/ui/frmNewProject.png)

```

2024-03-08 03:36 UTC, Meng-Heng commented on developer/17.0/context/new.md
> +![New File dialog](/cdn/dev/img/developer/120/ui/frmNew.4a0d546e5aa489e824c5bfd8dfa8a90f.png)
```suggestion
![New File dialog](/cdn/dev/img/developer/120/ui/frmNew.png)

```

2024-03-08 03:36 UTC, Meng-Heng commented on developer/17.0/context/options.md
> +![Options dialog - General tab](/cdn/dev/img/developer/120/ui/frmOptions_General.1c06f87249deec5c523683e2c591f390.png)
```suggestion
![Options dialog - General tab](/cdn/dev/img/developer/120/ui/frmOptions_General.png)

```

2024-03-08 03:36 UTC, Meng-Heng commented on developer/17.0/context/options.md
> +![Options dialog - Editor tab](/cdn/dev/img/developer/120/ui/frmOptions_Editor.d06167e9dfbd868a8f0c6efb02f0f142.png)
```suggestion
![Options dialog - Editor tab](/cdn/dev/img/developer/120/ui/frmOptions_Editor.png)

```

2024-03-08 03:36 UTC, Meng-Heng commented on developer/17.0/context/options.md
> +![Options dialog - Debugger tab](/cdn/dev/img/developer/120/ui/frmOptions_Debugger.e08156c683984826c1ed3f3e131c87de.png)
```suggestion
![Options dialog - Debugger tab](/cdn/dev/img/developer/120/ui/frmOptions_Debugger.png)

```

2024-03-08 03:38 UTC, Meng-Heng commented on developer/17.0/context/options.md
> +![Options dialog - Character Map tab](/cdn/dev/img/developer/120/ui/frmOptions_CharacterMap.63fcb20b6e0b39eb3ccaab04676df102.png)
```suggestion
![Options dialog - Character Map tab](/cdn/dev/img/developer/120/ui/frmOptions_CharacterMap.png)

```

2024-03-08 03:38 UTC, Meng-Heng commented on developer/17.0/context/project.md
> +![Project window - Welcome tab](/cdn/dev/img/developer/100/ui/frmProject_Welcome.eb24e7d3dac3bb95aabacb4df14e8521.png)
```suggestion
![Project window - Welcome tab](/cdn/dev/img/developer/100/ui/frmProject_Welcome.png)

```

2024-03-08 03:38 UTC, Meng-Heng commented on developer/17.0/context/project.md
> +![Project window - Keyboards tab](/cdn/dev/img/developer/100/ui/frmProject_Keyboards.943bd2c8a186ca4cad08d6a0e14e2a3e.png)
```suggestion
![Project window - Keyboards tab](/cdn/dev/img/developer/100/ui/frmProject_Keyboards.png)

```

2024-03-08 03:39 UTC, Meng-Heng commented on developer/17.0/context/project.md
> +![Project window - Packaging tab](/cdn/dev/img/developer/100/ui/frmProject_Packaging.26e4ad6dee0cd000a3f8e7f078810fe5.png)
```suggestion
![Project window - Packaging tab](/cdn/dev/img/developer/100/ui/frmProject_Packaging.png)

```

2024-03-08 03:39 UTC, Meng-Heng commented on developer/17.0/context/project.md
> +![Project window - Distribution tab](/cdn/dev/img/developer/120/ui/frmProject_Distribution.4192eebc4b3daba75bd6aec206978920.png)
```suggestion
![Project window - Distribution tab](/cdn/dev/img/developer/120/ui/frmProject_Distribution.png)

```

2024-03-08 03:39 UTC, Meng-Heng commented on developer/17.0/context/startup.md
> +![Startup window](/cdn/dev/img/developer/100/ui/frmStartup.4ad8404bf7b451ff4cca860896142486.png)
```suggestion
![Startup window](/cdn/dev/img/developer/100/ui/frmStartup.png)

```

2024-03-08 03:41 UTC, Meng-Heng commented
Thank you @darcywong00. Please review.

2024-03-12 21:28 UTC, mcdurdin requested changes
Thanks @Meng-Heng for this work -- it's looking good; I have just a few small changes requested.

2024-03-14 07:10 UTC, Meng-Heng commented on developer/17.0/context/debug.md
> +    **Debug** menu.
```suggestion
    **Select System Keyboard** from the **Debug** menu.
```

2024-03-21 06:31 UTC, mcdurdin approved these changes
LGTM, just a couple of typos which I will go ahead and correct

2024-03-21 06:31 UTC, mcdurdin commented on developer/17.0/context/character-map.md
> +edit the filter is available by clicking the [...] button.
```suggestion
edit the filter is available by clicking the \[...\] button.
```

Because `[` and `]` are used to indicate a link in Markdown, we should continue to escape them with `\`

2024-03-21 06:31 UTC, mcdurdin commented on developer/17.0/context/keyboard-editor.md
> +    and the key code matches the pattern `U_xxxx[yyyy...]`
```suggestion
    and the key code matches the pattern `U_xxxx[_yyyy...]`
```

2024-03-21 06:31 UTC, mcdurdin commented on developer/17.0/context/keyboard-editor.md
> +    -   `U_####[####]` is used as a shortcut for a key that
```suggestion
    -   `U_####[_####]` is used as a shortcut for a key that
```

2024-03-21 06:59 UTC, merged