feat: keyboard help files now have keyboard download links
keymanapp/help.keyman.com pull request #1287
Opened 2024-05-28 08:12 UTC by Meng-Heng

Fixes: #806

Please check the KeymanHosts link. 
It was not linking to keyman.com and it might be that I'm on localhost.

2024-05-29 00:20 UTC, mcdurdin requested changes
This is pretty close; I have some tidyup comments and one bugfix for you :grin:

2024-05-29 00:20 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +    $string.= "<li><a href='{$KeymanHosts->keyman_com}/keyboards/$kbdid'>Download $keyboardname</a></li>";
The `KeymanHosts` reference here was incorrect, so it was emitting a blank string, making this a relative path instead of pointing to keyman.com.

```suggestion
    $string.= "<li><a href='".KeymanHosts::Instance()->keyman_com."/keyboards/$kbdid'>Download $keyboardname</a></li>";
```

2024-05-29 00:20 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +    if(empty($pagename)) $pagename = '';
```suggestion
```

2024-05-29 00:20 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +        echo $version_history, $download;
```suggestion
        echo $version_history;
      if(!empty($download_link_html)) {
        echo $download_link_html;
      }
```

2024-05-29 00:20 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +  function download_keyboard($pagename) {
```suggestion
  function build_download_keyboard_link_html() {
```

We don't use the `$pagename` variable, so don't include it.

2024-05-29 00:20 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +    $download = download_keyboard($pagename);
The variable name `$download` is a little bit too generic (`$version_history` is also not great but that's a separate problem).

Can you call it `$download_link_html` -- that will be less likely to be a problem in the future.

```suggestion
    $download_link_html = build_download_keyboard_link_html();
```

2024-05-29 00:20 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +    global $version_history, $download;
```suggestion
    global $version_history, $download_link_html;
```

2024-05-29 00:20 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +    global $version_history, $download;
```suggestion
    global $version_history, $download_link_html;
```

2024-05-29 00:20 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +  define('KEYMAN', KeymanHosts::Instance()->keyman_com);
```suggestion
```

We're not using this define elsewhere, so let's not include it

2024-05-30 03:36 UTC, mcdurdin approved these changes
Let's remove the `$keyboardname` variable as it is only used once, and is confusing to have together with the `$kbdname` variable. Apart from that, LGTM

2024-05-30 03:36 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +    $string.= "<li><a href='".KeymanHosts::Instance()->keyman_com."/keyboards/$kbdid'>Download $keyboardname</a></li>";
```suggestion
    $string.= "<li><a href='".KeymanHosts::Instance()->keyman_com."/keyboards/$kbdid'>Download $kbdid keyboard</a></li>";
```

2024-05-30 03:36 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +    global $kbdname, $kbdid, $keyboardname;
```suggestion
    global $kbdname, $kbdid;
```

2024-05-30 03:36 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +        $keyboardname = $sub[0] . ' keyboard';
```suggestion
```

2024-05-30 03:36 UTC, mcdurdin commented on _includes/includes/kb_doc_template.php
> +    global $keyboardname, $kbdid; // from head() function
```suggestion
    global $kbdid; // from head() function
```

2024-05-30 03:41 UTC, Meng-Heng commented on _includes/includes/kb_doc_template.php
> +    $string.= "<li><a href='".KeymanHosts::Instance()->keyman_com."/keyboards/$kbdid'>Download $keyboardname</a></li>";
Right! I should've use it like this 😃

2024-05-30 03:42 UTC, Meng-Heng reviewed
Suggestions applied.

2024-05-30 05:25 UTC, merged