docs: Add remaining Keyman Engine for Android API's for KMManager
keymanapp/help.keyman.com pull request #1294
Opened 2024-06-03 13:00 UTC by darcywong00

This adds remaining API pages to KMManager pointed out in an earlier review comment

https://github.com/keymanapp/help.keyman.com/blob/73c9bc1991f56b9dc99fbe2eea924debf40be25d/developer/engine/android/18.0/KMManager/index.md?plain=1#L179-L180

              Is this missing a separate page?

_Originally posted by @mcdurdin in https://github.com/keymanapp/help.keyman.com/pull/1268#discussion_r1604385682_

2024-06-18 21:53 UTC, mcdurdin requested changes
A fair few typos; so sorry for all the comments!

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/executeHardwareKeystroke.md
> +| value  | Description    |
```suggestion
| Value  | Description    |
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/executeHardwareKeystroke.md
> +| 0x2000 | No scroll lock |
Caps lock was missing!

```suggestion
| `0x0100` | Caps lock      |
| `0x0200` | No caps lock   |
| `0x0400` | Num lock       |
| `0x0800` | No Num lock    |
| `0x1000` | Scroll         |
| `0x2000` | No scroll lock |
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/executeHardwareKeystroke.md
> +: lock state
```suggestion
: lock state. If neither the on or off state is specified for a lock key, then it is treated as unknown state for keyboard rule matching.
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getKMKeyboard.md
> +The `getKMKeyboard()` method returns the KMKeyboard for the specified keyboard type.
KMKeyboard should link to the type

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getLexicalModelInfo.md
> +Returns a dictionary containing information on the specified lexical model.
The dictionary should be documented here (and the type `Hashmap<String, String>`

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/executeHardwareKeystroke.md
> +```
This is not a very helpful example, though -- where do we collect the various values from? Can we use an example which ties into an Android event?

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getLexicalModelInfo.md
> +: Non-negative position of the installed lexical model
Zero-based index?

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getLexicalModelInfo.md
> +Use this method to get details about a sepcified lexical mode. (language and keyboard information)
```suggestion
Use this method to get details about a specified lexical model. (language and keyboard information)
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getLexicalModelInfo.md
> +KMManager.getLexicalModelInfo(Context context, int index)
```suggestion
HashMap<String,String> KMManager.getLexicalModelInfo(Context context, int index)
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/executeHardwareKeystroke.md
> +KMManager.executeHardwareKeystroke(int code, int shift, KeyboardType keyboard, int lstates, int eventModifiers)
```suggestion
bool KMManager.executeHardwareKeystroke(int code, int shift, KeyboardType keyboard, int lstates, int eventModifiers)
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getKMKeyboard.md
> +KMManager.getKMKeyboard(KeyboardType type)
```suggestion
KMKeyboard KMManager.getKMKeyboard(KeyboardType type)
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getKMKeyboard.md
> +Returns the KMKeyboard object.
Link to the KMKeyboard type?

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getLexicalModelsList.md
> +KMManager.getLexicalModelsList(Context context)
```suggestion
ArrayList<HashMap<String, String>> KMManager.getLexicalModelsList(Context context)
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getLexicalModelsList.md
> +Use this method to get details of all the installed lexical models.
The dictionary should be documented, perhaps link to `getLexicalModelInfo`?

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/lexicalModelExists.md
> +KMManager.lexicalModelExists(Context context, String packageID, String languageID, String modelID)
```suggestion
bool KMManager.lexicalModelExists(Context context, String packageID, String languageID, String modelID) 
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/lexicalModelExists.md
> +    boolean exists = KMManager.lexicalModelExists(context, "nrc", "en", "en.mtnt";
```suggestion
    boolean exists = KMManager.lexicalModelExists(context, "nrc.en.mtnt", "en", "nrc.en.mtnt");
```

I am not 100% sure of this, but I don't think the original example was right?

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/lexicalModelExists.md
> +* [getLexicalModelInfo](getLexicalModelInfo())
```suggestion
* [`getLexicalModelInfo()`](getLexicalModelInfo)
```

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/setCanRemoveKeyboard.md
> +```
````suggestion
```java
    void KMManager.setCanRemoveKeyboard(boolean newValue)
```
````

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/setCanRemoveKeyboard.md
> +Use this method to grant Keyman Engine for Android permission to remove keyboards from the keyboard list. If set to `false`, the installed keyboard list is permanent.
Is this to allow the end user to remove the keyboard? I'm not clear

2024-06-18 21:53 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/setCanRemoveKeyboard.md
> +* [canRemoveKeyboard()](canRemoveKeyboard)
```suggestion
* [`canRemoveKeyboard()`](canRemoveKeyboard)
```

2024-06-19 08:20 UTC, darcywong00 commented on developer/engine/android/18.0/KMManager/getLexicalModelInfo.md
> +: Non-negative position of the installed lexical model
```suggestion
`index`
: Zero-based index of the installed lexical model
```

2024-06-19 08:32 UTC, darcywong00 commented on developer/engine/android/18.0/KMManager/executeHardwareKeystroke.md
> +```
These look to be determined from `(int keyCode, KeyEvent event)`

https://github.com/keymanapp/keyman/blob/e4b0d1859c5517db0dd963a283a364ca2f284425/android/KMEA/app/src/main/java/com/keyman/engine/KMHardwareKeyboardInterpreter.java#L24-L74

2024-06-19 08:41 UTC, darcywong00 commented on developer/engine/android/18.0/KMManager/getKMKeyboard.md
> +Returns the KMKeyboard object.
Hm, that might be a separate PR. I'm not sure I saw a page for KMKeyboard.
(To put at /developer/engine/android/18.0/#toc-classes ?)

2024-06-25 20:36 UTC, darcywong00 commented on developer/engine/android/18.0/KMManager/getKMKeyboard.md
> +The `getKMKeyboard()` method returns the KMKeyboard for the specified keyboard type.
Added KMKeyboard page and link in 7f99859dd47d3bc10e728dfd695a5599b3d9f20c

2024-06-25 20:37 UTC, darcywong00 commented
I think I've addressed all the comments so far. Ready to re-review

2024-07-02 09:48 UTC, mcdurdin approved these changes
Approving but I think there are future TODOs. Ideally, the examples will include surrounding code to help clarify when and where a function may be called

2024-07-02 09:48 UTC, mcdurdin commented on developer/engine/android/18.0/KMKeyboard/index.md
> +<!-- Fill in examples of how to use, etc. -->
TODO

2024-07-02 09:48 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/executeHardwareKeystroke.md
> +```
Hmm, should this be a TODO for future improvement then?

2024-07-02 09:48 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getKMKeyboard.md
> +Returns the KMKeyboard object.
TODO for future improvement

2024-07-02 09:48 UTC, mcdurdin commented on developer/engine/android/18.0/KMManager/getLexicalModelsList.md
> +Use this method to get details of all the installed lexical models.
This is still TODO

2024-07-02 13:43 UTC, merged