feat: two samples of integrating keyman videos onto help.keyman.com
keymanapp/help.keyman.com pull request #1713
Opened 2024-11-25 09:42 UTC by Meng-Heng

follow: #1712

video sample:

https://github.com/user-attachments/assets/77c48f4e-d7e2-4e56-b4dd-74f1578f2903

Should we use the `<iframe>` tag or use js onclick to set the `<iframe>`?

2024-12-05 06:32 UTC, mcdurdin requested changes
I like the idea of not embedding the video until a img preview is clicked; we'll need to tweak the code slightly to get it to work across multiple thumbnails 

(This may not be relevant with the requested change, but as a side note, the `getElementById()` call result was not checked -- if a page did not have a matching element, it would return null, causing an error on `t.addEventListener` line.)

2024-12-05 06:32 UTC, mcdurdin commented on cdn/dev/js/videoloader.js
> +    t.addEventListener("click", function() {
I think we need to use [`querySelectorAll`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) instead of `getElementById`, and match on any element that has the appropriate `data-video` attribute, so we can have multiple thumbnails in the same document. That means then we need to add an event listener for each element found, in a loop.

2024-12-05 07:54 UTC, Meng-Heng commented on cdn/dev/js/videoloader.js
> +    t.addEventListener("click", function() {
Yes, I'll look into this.

2024-12-09 04:08 UTC, mcdurdin reviewed
This is looking good. A few minor style changes requested!

2024-12-09 04:08 UTC, mcdurdin commented on developer/videos/index.md
> +    <img id="keymanThumbnails" data-video="https://www.youtube.com/embed/qoLpuah72kw" src="https://img.youtube.com/vi/qoLpuah72kw/maxresdefault.jpg" width="600px">
* `id` should not be repeated across multiple elements -- perhaps use `class` instead.
* Instead of `keymanThumbnails` can we use `video-thumbnail`?
* 
```suggestion
    <img class="video-thumbnail" data-video="https://www.youtube.com/embed/qoLpuah72kw" src="https://img.youtube.com/vi/qoLpuah72kw/maxresdefault.jpg" width="600px">
```

2024-12-09 04:08 UTC, mcdurdin commented on cdn/dev/js/videoloader.js
> +})
Use an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) to prevent pollution of global namespace:
```suggestion
(function() {
  const thumbnailsList = document.querySelectorAll(".video-thumbnail");
  
  window.addEventListener('DOMContentLoaded', () => {
    thumbnailsList.forEach(thumbnail => {
  	  thumbnail.addEventListener('click', () => {
  
  		  if(thumbnail.hasAttribute('data-video')) {
          let videoId = thumbnail.getAttribute('data-video')
    		  thumbnail.outerHTML = "<iframe width='600' height='315' src='" + videoId + "' allowfullscreen></iframe>";
        }
      })
    })
  })
})();
```

* I've also renamed the variable `each` to `thumbnail` to better represent what it is.
* I renamed the selector from `#keymanThumbnails` to `.video-thumbnail` (a class rather than an id, and singular rather than plural, and 'video' instead of 'keyman' to clarify what it is for, and finally, using kebab-case instead of camelCase :grin:)

2024-12-09 05:36 UTC, Meng-Heng commented
Thanks @mcdurdin. I'm taking notes, this is so unfamiliar to me. 😅

2024-12-09 05:50 UTC, mcdurdin approved these changes
LGTM!

2024-12-11 14:07 UTC, merged