fix: links to the available version of docs
keymanapp/help.keyman.com pull request #1755
Opened 2024-12-16 06:00 UTC by Meng-Heng

2024-12-18 06:17 UTC, darcywong00 reviewed
Unsure how to handle anchored links

2024-12-18 06:17 UTC, darcywong00 commented on developer/language/guide/virtual-keys.md
> +## Virtual character keys
We might need to update all the links to these anchors. This one corresponds to l.84

which might work if we change that to `(#toc-virtual-character-keys).

I'm not sure we want to change all the links this way though.

2024-12-18 07:52 UTC, Meng-Heng commented on developer/language/guide/virtual-keys.md
> +## Virtual character keys
Hello @darcywong00. The changes of this PR shows this:
![image](https://github.com/user-attachments/assets/c2365e62-0dff-41a2-97ab-a050a81c4ce8)

Do you mean adding `{#toc-` in front of `virtual-character-keys}`, not removing them entirely? Also, may I know what is I.84? 😅

2024-12-18 07:58 UTC, darcywong00 commented on developer/language/guide/virtual-keys.md
> +## Virtual character keys
The abbreviation l.84 means "line 84" in the file (above). 
```md
keyboard, along with the specified modifier. [More info](#virtual-character-keys)
```

When I tried locally, clicking the "More info" links didn't work

I noticed the links in "On this page" did work though. And they had the toc- prefix...

2024-12-18 08:13 UTC, Meng-Heng commented on developer/language/guide/virtual-keys.md
> +## Virtual character keys
Thank you @darcywong00. I've seen the abbreviation once before but couldn't remember it. 

Would this fix be appropriate? the {#virtual-character-keys} showed up like this if not removed.
![image](https://github.com/user-attachments/assets/91b1e72b-d6a5-48e3-8281-5547a3fabaa6)

I am trying {#virtual-character-keys} on "More info" but no success.
![image](https://github.com/user-attachments/assets/d8ac2bfe-a0a8-4a8b-83cc-b4945989993d)

Only being scrolled to via clicking on "On this page", but the URL shows this:
`http://help.keyman.com.localhost:8055/developer/language/guide/virtual-keys#toc-virtual-character-keys-virtual-character-keys-`

I think `#toc-virtual-character-keys` was assigned as an `id` before converting to markdown.

2025-01-13 08:42 UTC, mcdurdin commented on developer/language/guide/virtual-keys.md
> +## Virtual character keys
> `#toc-virtual-character-keys`

The `#toc-` prefix is generated automatically and used for navigation internally in the page. The other hashtags were intended to be used as permanent anchors but it looks like they are not working.

2025-01-16 02:46 UTC, mcdurdin requested changes

2025-01-16 02:46 UTC, mcdurdin commented on developer/language/guide/virtual-keys.md
> +## Virtual character keys
We need to restore these anchors in this PR. See #1791.

2025-01-22 00:52 UTC, mcdurdin approved these changes

2025-01-22 00:52 UTC, merged