fix: Update KeyboardEventHandler
keymanapp/help.keyman.com pull request #228
Opened 2020-09-25 01:33 UTC by darcywong00

Split out the two interfaces, and add `onPackageInstalled` and `onLexicalModelInstalled`

2020-09-25 05:01 UTC, mcdurdin requested changes
Some changes please:

* Avoid using `.php` extension in links
* Consider writing new content in Markdown (use .md extension instead of .php)

2020-09-25 05:01 UTC, mcdurdin commented on developer/engine/android/14.0/KeyboardEventHandler/onPackageInstalled.php
> +<h3 id="Example:_Using_method” name="Example:_Using_method">Example: Using <code><?php echo $event.'()' ?></code></h3>
```suggestion
<h3 id="Example:_Using_method" name="Example:_Using_method">Example: Using <code><?php echo $event.'()' ?></code></h3>
```

2020-09-25 08:57 UTC, darcywong00 commented
I've converted the new content to .md. But I don't see how to set the `head(['title' => 'XYZ']);`

In the left navigation, both pages show as "Untitled page.md"

2020-09-28 04:41 UTC, mcdurdin commented
> I've converted the new content to .md. But I don't see how to set the `head(['title' => 'XYZ']);`

Yeah, sorry about that. There's a standard .md metadata section you can add:

```
---
title: my super web page
---
```

For an example, see https://raw.githubusercontent.com/keymanapp/help.keyman.com/staging/developer/cloud/package-version/1.0/index.md

2020-09-28 23:23 UTC, mcdurdin approved these changes
One line missed in the html->md changeover but LGTM

2020-09-28 23:23 UTC, mcdurdin commented on developer/engine/android/14.0/KeyboardEventHandler/onLexicalModelInstalled.md
> +The information dictionaries of the lexical-models installed from a lexical-model package with keys and values defined as <code>List&lt;HashMap&lt;String key, String value&gt;&gt;</code>.</dd>
```suggestion
The information dictionaries of the lexical-models installed from a lexical-model package with keys and values defined as `List<HashMap<String key, String value>>`.
```

2020-09-29 01:51 UTC, merged