keyboard submission via GitHub
keymanapp/help.keyman.com pull request #242
Opened 2020-10-07 21:08 UTC by DavidLRowe

This is a draft of submitting a keyboard via GitHub.

Comments, corrections, revisions welcome.

2020-10-08 03:02 UTC, darcywong00 commented on developer/keyboards/index.php
> +    <li><a href="starter">Starter Guide (deprecated)</a></li>
On the `developer/keyboards/starter/index.php` page,
* maybe also add "(deprecated)" 
* and add a link to the github guide

2020-10-08 03:10 UTC, darcywong00 commented
Thanks for making this guide! Hopefully, it will lessen your pain on keyboard submissions 😄 

btw, I think @mcdurdin is preferring new content to be written in Markdown instead of php.
Here's a link on how to format the titles
https://github.com/keymanapp/help.keyman.com/pull/228#issuecomment-699765788

2020-10-08 21:53 UTC, mcdurdin commented
Thank you David!

> btw, I think @mcdurdin is preferring new content to be written in Markdown instead of php.

Yes, I am annoying like this. Markdown is a much nicer format than HTML for this kind of document and makes maintenance much easier in the future. There are tools for converting automatically, such as https://www.browserling.com/tools/html-to-markdown -- just paste the HTML section, not the PHP section.

The thing that you will need to do yourself is insert the right metadata at the top, as described in the link Darcy gave, viz: there's a standard .md metadata section you can add:

```
---
title: my super web page
---
```

For an example, see https://raw.githubusercontent.com/keymanapp/help.keyman.com/staging/developer/cloud/package-version/1.0/index.md

2020-10-12 23:11 UTC, DavidLRowe commented
Yes, you had mentioned using markdown, but by the time I got to this task I had forgotten and just copied files from the advanced folder.

I'll update the new files accordingly.

What about existing files? Are you planning to change them to markdown as well?

How do I link from a php file to a md file? (And from a md file to another md file?) Do I need to replace index.php with index.md and work down?

2020-10-12 23:26 UTC, mcdurdin commented
> What about existing files? Are you planning to change them to markdown as well?

We'll change files over time as we edit them -- not planning to do a major shift.

> How do I link from a php file to a md file? (And from a md file to another md file?) Do I need to replace index.php with index.md and work down?

* To link to other pages, just don't include the file extension; e.g. if the target is called /developer/foo.php, then use `<a href='/developer/foo'>`.

* For index.php or index.md, leave off the whole filename, for example if you have /developer/creating-emoji-keyboards/index.md, you would reference that as `<a href='/developer/creating-emoji-keyboards/'>`.

* Finally, also use relative paths as far as possible in links (e.g. use `foo` instead of `/developer/foo` if you can, or `../developer/foo` to go up a level). For a relative reference to index use `<a href="index">` (which will redirect silently to the folder URL)

2020-10-13 22:33 UTC, DavidLRowe commented
What about PHP include statements, for example: 
```
<?php
    include('../_shared/development-tools.php');
?>
```

2020-10-13 22:38 UTC, mcdurdin commented
> What about PHP include statements, for example:

No, you can't use PHP include statements. The content of .md files is intended to be static without server-side changes, which makes them more stable long term and easier to maintain.

2020-10-13 22:40 UTC, DavidLRowe commented
So, copy the information from the include into the file?

2020-10-13 22:43 UTC, mcdurdin commented
Yes, the file needs to be static. 

Duplicate content is less of a problem here than having more complicated backend configuration. This is generally the case for documentation -- if we have a lot of duplicate content, that's an argument for restructuring the content, not using back-end techniques to copy the same content to multiple pages.

2020-10-15 01:02 UTC, DavidLRowe commented
This ended up being trickier than it looked. I also corrected some errors in the original .php files and did some shuffling of content.

Needs more than a cursory review, including testing all the links!

2020-10-15 02:21 UTC, mcdurdin commented
> This ended up being trickier than it looked. I also corrected some errors in the original .php files and did some shuffling of content.

Thank you! It's much appreciated. We automatically check links when we merge to the staging server so will do so then, if that's okay.

2020-10-20 03:14 UTC, darcywong00 commented
On the /developer/keyboards/advanced/index.php page, there's still some mentions/links to the "Starter guide" that you can change to the GitHub guide. (editing the php should be fine, no need to convert that to .md)

2020-10-20 03:18 UTC, darcywong00 commented on developer/keyboards/github/index.md
> +<dl>
I think the `<dl>` and `<dt>` tags are interfering with the links. You can remove them (keep the empty lines between the steps).

2020-10-20 03:20 UTC, darcywong00 commented on developer/keyboards/github/step-0.md
> +# Preliminary Step: Is Your Keyboard Ready?
The `title:` formatting already generates this title on the page, so this line can be removed.
Also applies to each  step-*.md in the guide.

2020-10-20 03:33 UTC, darcywong00 commented on developer/keyboards/github/step-0.md
> +<dt>`source\help\<keyboard>.php`</dt>
We may need to investigate how markdown with `<dl><dt> <dd>` tags. In my browser, the `<keyboard>` is treated as an invalid tag so the page renders
> source\help\\.php

2020-11-16 21:42 UTC, mcdurdin requested changes
I don't have permission to update the Markdown parser here so we will add it as a new PR and we can rebase this PR once it lands.

(Note, the version of Parsedown that is on keymanapp/keyman.com#192 is the one that we will use here).

2020-11-16 21:42 UTC, mcdurdin commented on developer/keyboards/github/step-0.md
> +<dt>`source\help\<keyboard>.php`</dt>
HTML snippets within Markdown cannot themselves contain Markdown. Best to avoid HTML altogether if we can.

Fortunately, with a minor update to our Markdown parser, we can support definition lists (⬅ this makes me Happy Marc).

To do a markdown definition list:

```
`build\`
  : not stored in the repository; output files will go here

`extras\`
  : other related files, e.g. Word documents, databases, experimental files
```

(The indent is not necessary before the colon, but it may make it easier to read the source).

2020-11-16 21:42 UTC, mcdurdin commented on developer/keyboards/github/index.md
> +<dt>[Step 3: Submitting a GitHub Pull Request](step-3)</dt>
This should not be a definition list because it only contains terms. Instead, just make it a bullet list `* step 0` ...

2020-12-11 19:50 UTC, DavidLRowe commented
Sorry to have left this sitting so long. It dropped off my radar. I went to look for it online and realised that it hadn't been merged because more work was needed. 

I've attempted to address the problems you both (@darcywong00 and @mcdurdin) have pointed out. I used "xyz" rather than "keyboard" in angle brackets to avoid display issues.

Ignore my comment about list text being repeated (in the "Update step-0.md" commit. What I was seeing was GitHub showing me deletions and additions when I previewed the changes.

In Step 2, I'm not really happy with the "One keyboard per folder" heading. I think the text has changed significantly and the header should probably change too. Any suggestions?!

2020-12-14 01:01 UTC, mcdurdin approved these changes
Looks good to me!

> Sorry to have left this sitting so long. It dropped off my radar. I went to look for it online and realised that it hadn't been merged because more work was needed.

No problems -- understand having many things to look after 😉 

> In Step 2, I'm not really happy with the "One keyboard per folder" heading. I think the text has changed significantly and the header should probably change too. Any suggestions?!

I'm not really coming up with any better ideas just now.

2020-12-14 04:22 UTC, DavidLRowe commented
@mcdurdin Thanks for catching the one I missed. I think it's ready to merge now.

2020-12-14 04:24 UTC, merged

2020-12-14 04:25 UTC, mcdurdin commented
Thank you @DavidLRowe for this excellent PR 🥇  I always get excited when we get documentation improvements -- we don't do enough of them I think... 😄