Chore/kmea/kmmanager 14
keymanapp/help.keyman.com pull request #257
Opened 2020-11-20 05:26 UTC by darcywong00

This starts to address #180

Add new KMManager API's
* getDefaultKeyboard()
* setDefaultKeyboard()
* getMaySendCrashReport() (See keymanapp/keyman#3825)
* setMaySendCrashReport()

* Update the add/set Keyboard methods to use the new Keyboard type. (Mark HashMap dictionaries as *(Deprecated)*)

2020-11-25 20:01 UTC, mcdurdin requested changes
A few changes in style requested

2020-11-26 07:25 UTC, darcywong00 commented on developer/engine/android/14.0/KMManager/addKeyboard.php
> +      "",               // URL to latest .kmp file
Either `null` or `""` work for those fields.

If the help URL is not a welcome.htm file, the Keyboard constructor will make the help link https://help.keyman.com/keyboard/<keyboardID>

If the latest kmp link is null or empty, a resource update is not available.

2020-11-26 07:54 UTC, darcywong00 commented on developer/engine/android/14.0/KMManager/getCurrentKeyboardInfo.php
> +<h2 id="Syntax" name="Syntax">Syntax (Deprecated)</h2>
OK. KMManager wasn't noting history, so I added those section

2020-11-26 20:28 UTC, mcdurdin approved these changes

2020-11-26 20:28 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/addKeyboard.php
> +      "",               // URL to latest .kmp file
Okay, for the example can we use `null` please?

2020-11-26 23:40 UTC, merged