chore(common): Add link to knowledge base
keymanapp/help.keyman.com pull request #259
Opened 2020-11-25 14:35 UTC by ermshiperete

2020-11-25 20:06 UTC, mcdurdin requested changes
Can you also add the link to /products/index.php -- perhaps in a separate section?

It would be better to have a `<hr>` before the KB link in the menu, given it is not a product, but I'm not sure how it will look.

2020-11-25 20:06 UTC, mcdurdin commented on Readme.md
> +   to edit the hosts file.)
```suggestion
6. Start an elevated instance of Notepad (that is, use "Run as Administrator" when starting
   Notepad), load "C:\WINDOWS\System32\drivers\etc\hosts" and add the line
   `127.0.0.1  help.keyman.com.local`.
```

I'd prefer not to include this diagnostic stuff here.

2020-11-26 10:41 UTC, ermshiperete commented
> Can you also add the link to /products/index.php -- perhaps in a separate section?

Done. Please feel free to improve the wording.

2020-11-26 20:21 UTC, mcdurdin approved these changes

2020-11-27 07:53 UTC, merged