fix(android): Add content for KMManager lexical model APIs
keymanapp/help.keyman.com pull request #311
Opened 2021-02-05 03:45 UTC by darcywong00

Fixes #302

Also adds content for more of KMManager lexical model APIs (not all)

2021-02-08 23:08 UTC, mcdurdin requested changes
Good first cut. A few typos and cleanups and some suggestions for content. Also managed to critique the API a little which you may want to extract into a new issue for the future on the keyman repo... 😆

2021-02-08 23:08 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/index.php
> +  <dd>returns a String to use as a shared preference key to store whether the LMLayer should enable suggestions for a given language.</dd>
```suggestion
  <dt><code><a href='getLanguageCorrectionPreferenceKey'>getLanguageCorrectionPreferenceKey()</a></code></dt>
  <dd>returns a String to use as a shared preference key to store whether the LMLayer should enable corrections for a given language</dd>

  <dt><code><a href='getLanguagePredictionPreferenceKey'>getLanguagePredictionPreferenceKey()</a></code></dt>
  <dd>returns a String to use as a shared preference key to store whether the LMLayer should enable suggestions for a given language.</dd>
```

2021-02-08 23:08 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/registerAssociatedLexicalModel.md
> +```javascript
```suggestion
```java
```

2021-02-08 23:08 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/registerAssociatedLexicalModel.md
> +: The language ID
```suggestion
`langId`
: The BCP 47 language ID
```

2021-02-08 23:08 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/registerAssociatedLexicalModel.md
> +```javascript
```suggestion
```java
```

2021-02-08 23:08 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/registerLexicalModel.md
> +```javascript
```suggestion
```java
```

2021-02-08 23:08 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/registerLexicalModel.md
> +: A dictionary of lexical model information with keys and values defined as `HashMap<String key, String value)`.
```suggestion
`lexicalModelInfo`
: A dictionary of lexical model information with keys and values defined as `HashMap<String key, String value)`.
```

It would be good to define what needs to be in this hash map. This use of hash maps is definitely a candidate for refactoring in a future update of Keyman Engine -- we would include overloaded functions that take a proper object rather than this and deprecate the hash map based functions!

2021-02-09 02:15 UTC, darcywong00 commented on developer/engine/android/14.0/KMManager/getLanguageCorrectionPreferenceKey.md
> +The String is a constant of `langId` plus a suffix `.mayCorrect`.
> Is this shared preference name required for the system keyboard? Does Keyman Engine depend on it?

KMEA uses the key as an override. If the preference keys don't exist or aren't set, the default is `true`.

So is the intent in documenting here to allow keyboard creators to set their own preference to disable/enable corrections and predictions?

We can certainly add a `keyman` prefix.

2021-02-09 02:49 UTC, darcywong00 commented on developer/engine/android/14.0/KMManager/getLanguageCorrectionPreferenceKey.md
> +The String is a constant of `langId` plus a suffix `.mayCorrect`.
We went spelunking in the code and determined:
* these preferences are saved in a KMAPreferences file, so it won't be polluting keyboard apps
* it would be better at a future release for the apps to manage these and pass the values to KMManager to determine when to override.

For now, we'll mark these as "experimental" and likely to go away to dissuade usage

2021-02-09 22:02 UTC, mcdurdin approved these changes
LGTM

2021-02-09 22:02 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/getLanguageCorrectionPreferenceKey.md
> +The usage of this preference key is experimental and likely to be deprecated in a future release of KMEA.
```suggestion
The usage of this preference key is experimental and likely to be deprecated in a future release of Keyman Engine for Android.
```

(Let's avoid using "KMEA" as far as possible. "Keyman Engine" or "Keyman Engine for Android" are appropriate.

2021-02-09 22:02 UTC, mcdurdin commented on developer/engine/android/14.0/KMManager/getLanguagePredictionPreferenceKey.md
> +The usage of this preference key is experimental and likely to be deprecated in a future release of KMEA.
```suggestion
The usage of this preference key is experimental and likely to be deprecated in a future release of Keyman Engine for Android.
```

2021-02-09 23:45 UTC, merged