fix(ios): Migrate help to markdown
keymanapp/help.keyman.com pull request #315
Opened 2021-02-09 03:28 UTC by darcywong00

This adds the first point of #287 in migrating the iOS help to markdown

2021-02-09 03:30 UTC, darcywong00 commented on products/iphone-and-ipad/14.0/about/system-requirements.md
> +iOS 9.
Is this correct, @jahorton ? I got it from https://keyman.com/iphone-and-ipad/

2021-02-09 08:50 UTC, jahorton commented on products/iphone-and-ipad/14.0/about/system-requirements.md
> +iOS 9.
<img width="411" alt="Screen Shot 2021-02-09 at 3 49 25 PM" src="https://user-images.githubusercontent.com/25213402/107338707-71446300-6aee-11eb-8941-396ee1bcb799.png">

2021-02-09 08:55 UTC, jahorton requested changes
Just a few small details worth tweaking first.

2021-02-09 08:55 UTC, jahorton commented on products/iphone-and-ipad/14.0/about/whatsnew.md
> +* Choose associated language(s) when keyboard is installed (#3437)
Don't forget keyboard search itself!

2021-02-09 08:55 UTC, jahorton commented on products/iphone-and-ipad/14.0/basic/installing-custom-keyboards.md
> +If downloading a custom keyboard from the internet, click the link to your custom keyboard package file.
"or dictionary"

2021-02-09 08:55 UTC, jahorton commented on products/iphone-and-ipad/14.0/basic/installing-custom-keyboards.md
> +### Finding the File (iOS 11+ only)
Sadly... `iOS 13+ only`.  See https://github.com/keymanapp/keyman/issues/4017.

It's been an issue for far longer than the issue's date, so it's best that we just own up to that limitation for now.

2021-02-10 02:33 UTC, jahorton approved these changes

2021-02-10 02:33 UTC, merged