docs: first cut auto convert html to md
keymanapp/help.keyman.com pull request #586
Opened 2022-08-09 00:46 UTC by rc-swag

Convert the core api docs to markdown.

2023-03-21 00:12 UTC, darcywong00 commented on developer/core/desktop/16.0/c-api/state-api.md
> +km\_kbp\_state\_to\_json()
The link-checker during the CI build failed because the page
> Getting links from: http://localhost:8888/developer/core/desktop/16.0/json-schema
>├─BROKEN─ http://localhost:8888/developer/core/desktop/16.0/c-api/state-api.php#km_kpb_state_to_json (HTTP_404)

So the  json-schema page will need to be updated to link to this section. (I don't remember the details for setting up a Markdown anchor)

2023-03-21 00:14 UTC, darcywong00 commented on developer/core/desktop/16.0/c-api/state-api.md
> +km\_kbp\_state\_to\_json()
Ah, it's something like
```
/developer/core/desktop/16.0/c-api/state-api#toc-km-kbp-state-to-json-
```

2023-03-21 00:24 UTC, darcywong00 commented on developer/core/desktop/16.0/c-api/state-api.md
> +```
```suggestion
```c
```
This will apply C-syntax highlighting for the code blocks. (Probably applies to all the code blocks on this PR)

2023-03-23 04:00 UTC, rc-swag commented
Internal Links 
Using the PHP  Markdown Extra syntax defined [here](https://michelf.ca/projects/php-markdown/extra/#spe-attr). The Headers now have an id set that could then be linked back to. 
```
Header 1            {#header1}
========
```
Then you can create links to different parts of the same document like this:
```
[Link back to header 1](#header1)
```
Things to note I was able to use this for the majority of the links and they were already linking to "Headers".
For Non-headers for example `KM_KBP_IT_END`  or `KM_KBP_OPT_KEYBOARD` The nearest header of `Values` worked well as this was the section that had all the definitions.
Finally, there were some links that just linked a few lines up to the definition of function parameters suchas `out`, `buf` and `state`. These were just completely removed as they did not really achieve much as what they where linking to in most cases was only a few lines above the link.

2023-03-28 06:33 UTC, mcdurdin requested changes
This is looking good. I've requested some changes to the style of markdown used, particularly for headings and definition lists. But those changes are not critical.

2023-03-28 06:33 UTC, mcdurdin commented on developer/core/desktop/16.0/c-api/context-api.md
> +The context is the text prior to the insertion point (caret, cursor). The context is constructed by the Platform layer, typically by interrogating the Client Application. The context will be updated
Can we wrap all long lines? It makes future review much easier.

I use an extension in VS Code called [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) which does this pretty well

2023-03-28 06:33 UTC, mcdurdin commented on developer/core/desktop/16.0/c-api/context-api.md
> +title: Context
This probably needs to be a little longer, e.g. `Context - Keyman Core API` (same applies for titles in all files)

2023-03-28 06:33 UTC, mcdurdin commented on developer/core/desktop/16.0/c-api/context-api.md
> +===========================
I think I'd prefer to use the other form of headings for consistency with other pages on the site, and tweak the formatting slightly at the same time:

```suggestion
# `km_kbp_context_type` enum  {#km_kbp_context_type}
```

2023-03-28 06:33 UTC, mcdurdin commented on developer/core/desktop/16.0/c-api/context-api.md
> +-----------
Same thing re headings here and elsewhere in these docs:

```suggestion
## Description
```

2023-03-28 06:33 UTC, mcdurdin commented on developer/core/desktop/16.0/c-api/context-api.md
> +Values {#values}
This is a very generic link ref (`#values`). If we want to use it (I don't think we do), it should be `#km_kbp_context_type-values` or similar

2023-03-28 06:33 UTC, mcdurdin commented on developer/core/desktop/16.0/c-api/context-api.md
> +The context item contains a positional marker which must be accessed through the [`km_kbp_context_item.marker`](#km_kbp_context_item) union member.
```suggestion
* `KM_KBP_CT_END`
: A [`km_kbp_context_item`](#km_kbp_context_item) of this type marks the end of an array of context items.

* `KM_KBP_CT_CHAR`
: The context item contains a Unicode Scalar Value which must be accessed through the [`km_kbp_context_item.character`](#km_kbp_context_item) union member.

* `KM_KBP_CT_MARKER`
: The context item contains a positional marker which must be accessed through the [`km_kbp_context_item.marker`](#km_kbp_context_item) union member.
```

We can use [Definition Lists](https://michelf.ca/projects/php-markdown/extra/#def-list) to improve formatting here.

2023-03-28 06:33 UTC, mcdurdin commented on developer/core/desktop/16.0/c-api/index.md
> +title: C API Reference
```suggestion
title: Reference - Keyman Core API
```

2023-03-29 00:59 UTC, rc-swag commented on developer/core/desktop/16.0/c-api/context-api.md
> +Values {#values}
Yes will change the name as it could avoid a duplicate clash also, but we do already use it as mentioned [here](https://github.com/keymanapp/help.keyman.com/pull/586#issuecomment-1480569195) all the previous links in the php version that went direct to the types `KM_KBP_CT_???` now have links the heading above as it is sufficient and works with markdown.

2023-03-30 03:28 UTC, rc-swag commented on developer/core/desktop/16.0/c-api/context-api.md
> +title: Context
It is good in isolation, although the left-hand tree view looks a little redundant now. 
![image](https://user-images.githubusercontent.com/58423624/228721182-980941eb-0953-4b35-9e1d-fca4d236d19e.png)

2023-03-30 03:35 UTC, rc-swag commented
I change then reverted the
 ```# km\_kbp\_action\_item struct {#km_kbp_action_item} ``` to 
# `km_kbp_action_item` struct {#km_kbp_action_item}```

As the backtick overides the heading in markdown.  So escaping the with \ needs to stay.

I added the lists but they made no difference the rendering visually, even though the html now has the <dl > tags.

All the heading are updated to the same style used in other markdown documents on the site.

2023-04-05 07:47 UTC, mcdurdin approved these changes

2023-04-05 22:05 UTC, merged