chore: Updates to work with Docker
keymanapp/help.keyman.com pull request #599
Opened 2022-09-14 01:17 UTC by darcywong00

Follow-on to #588

Thanks to some pair-programming with @mcdurdin , this cleans up some of the redirects and has the site working with Docker.

A TODO to investigate, the keyboard links are generating a warning:

> Warning: session_start(): Cannot start session when headers already sent in /var/www/html/_includes/includes/head.php on line 3

Also, the keyboard php extension isn't getting removed, so the redirect is loading something like:
http://localhost:8055/keyboard/georgian/1.0/georgian.php

I copied the `composer check-links` step to `check-composer-links` so we can check links with either help.keyman.com.local or localhost:8055.

2022-09-14 08:20 UTC, ermshiperete approved these changes

2022-09-14 08:21 UTC, ermshiperete commented on .htaccess
> +RewriteCond "%{DOCUMENT_ROOT}/$1.php" -f
> Also, the keyboard php extension isn't getting removed, so the redirect is loading something like:
http://localhost:8055/keyboard/georgian/1.0/georgian.php

Is this the reason? (We now expect a top-level file whereas previously it could be in a subdirectory)

2022-09-14 08:25 UTC, darcywong00 commented on .htaccess
> +#Not needed if local apache.conf includes this
It's needed with the Docker image. I left the comment cause my local development had the path set in apache.conf.

2022-09-15 05:28 UTC, mcdurdin commented
Note: I'd like to review this tomorrow hopefully. Got buried today with too many things to do...

2022-09-15 23:18 UTC, mcdurdin requested changes
I'm not 100% sure on all the redirects -- mod_rewrite is pretty hard to work with... but it's looking pretty close.

2022-09-15 23:18 UTC, mcdurdin commented on .htaccess
> +RewriteRule "^(.+)/current-version(/.*)?" "$1/15.0$2"
```suggestion
RewriteRule "^(.+)/current-version(/.*)?$" "$1/15.0$2"
```

We want to make sure we capture the whole suffix. I think it will anyway given `.*` is greedy by default in PCRE, but including `$` clarifies our intent which helps for future maintenance!

I think you need to copy the same pattern down for the other current-version rules.

2022-09-15 23:18 UTC, mcdurdin commented on .htaccess
> +RewriteCond "%{DOCUMENT_ROOT}/$1.php" -f
```suggestion
RewriteCond "$1.php" -f
```

As @ermshiperete says, I think this should be restored to the original.

2022-09-15 23:18 UTC, mcdurdin commented on .htaccess
> +RewriteCond "%{DOCUMENT_ROOT}/$1.md" !-f
```suggestion
RewriteCond "$1" -d
RewriteCond "$1.php" !-f
RewriteCond "$1.md" !-f
```

I don't think we want the document root requirement here.

2022-09-15 23:18 UTC, mcdurdin commented on keyboard/.htaccess
> +RewriteRule "^(?!index.php|redir.php)([^/?]+)(/)?$" "/keyboard/redir.php?q=$1" [END]
```suggestion
RewriteRule "^(?!index.php|redir.php)([^/?]+)(/)?$" "/keyboard/redir.php?q=$1" [R,L]
```

This was a redirect, I think it still needs to be

2022-09-16 01:08 UTC, darcywong00 commented on .htaccess
> +RewriteCond "%{DOCUMENT_ROOT}/$1.php" -f
Done.

But the keyboard pages still show `.php` :disappointed:

2022-09-16 03:41 UTC, mcdurdin commented on .htaccess
> +RewriteCond "%{DOCUMENT_ROOT}/$1.php" -f
Ping me if you want to rubber-ducky on this next week?

2022-09-19 09:07 UTC, ermshiperete commented on _includes/errors/404.php
> +  // IIS uses REQUEST_URI; Apache using uri
```suggestion
  // IIS uses REQUEST_URI and _SERVER; Apache using uri and _REQUEST
```

I assume that's the way it is...

2022-09-21 22:46 UTC, darcywong00 commented on .htaccess
> +RewriteCond "{DOCUMENT_ROOT}/$1.php" -f
```suggestion
RewriteCond "$1.php" -f
```

> As @ermshiperete says, I think this should be restored to the original.

I tried the suggestion, but the keyboard pages failed to load

2022-09-22 02:10 UTC, darcywong00 commented on .htaccess
> +RewriteCond "{DOCUMENT_ROOT}/$1.php" -f
nvm, it's working now without `{DOCUMENT_ROOT}`

2022-09-22 02:28 UTC, darcywong00 commented
Currently, keyboard pages generate these Setnry [errors](https://sentry.io/organizations/keyman/issues/3592581591/?project=5983515&query=is%3Aunresolved)

> Warning: session_start(): Cannot start session when headers already sent

They seem to be caused from
https://github.com/keymanapp/help.keyman.com/blob/947929011fc35865a2bccbb5f1339bc71cdf6156/_includes/includes/head.php#L3

and go away when I remove that line?

2022-09-26 01:38 UTC, darcywong00 commented
hmm, the session seems fine with no changes to head.php

2022-09-26 10:23 UTC, mcdurdin approved these changes

2022-09-26 10:23 UTC, mcdurdin commented on .htaccess
> +RewriteCond "{DOCUMENT_ROOT}/$1" -d
This rule doesn't look correct? Does it need `{DOCUMENT_ROOT}`?

2022-09-27 02:18 UTC, merged