chore: Add builder scripts for Developers 🦭
keymanapp/help.keyman.com pull request #604
Opened 2022-09-27 02:44 UTC by darcywong00

Follow-on to #599 and joining the [build-utils](https://github.com/keymanapp/keyman/blob/master/resources/build/build-utils.md) movement

The first commit is seeding the builder scripts from the main repo.
I then removed the VERSION and Sentry bits.

Rather than having to memorize all the Docker incantations:

`./build.sh configure` - Installs dependencies
`./build.sh build` - Downloads docker image and starts the container. Once this is called, the site is accessible at http://localhost:8055
`./build.sh test` - Runs the link checker. Do we need to include lint?

Other  possible TODOs
clean - I haven't sorted how to clean up Docker images/containers.

2022-09-27 03:06 UTC, darcywong00 commented
At what point should tier.txt be created?

2022-09-27 03:56 UTC, mcdurdin reviewed
Conceptually I really like the idea.

One concern: we'll have to keep build-utils.sh in sync between repos. I am not sure how we best handle this, but read below for some potential mitigations.

There are also some assumptions in build-utils.sh that we should probably revisit before we go too far with using it cross-repo, e.g.:

* `$KEYMAN_ROOT` variable name is misleading and should probably be `$REPO_ROOT`
* We should remove any code specific to the keyman repo, e.g. `findTier`, `exportEnvironmentDefinitionScript` (and thus don't need that entry in .gitignore), `set_keyman_standard_build_path`, `printXCodeBuildScriptLogs`, `run_xcodebuild` ...

In fact, it might be better to split the builder_ script stuff into /resources/builder.inc.sh, on the Keyman repo side, and source include it from build-utils.sh (`. "$KEYMAN_ROOT/resources/builder.inc.sh`), and aim to make builder.inc.sh a cross-repo compatible script, including defining `$REPO_ROOT`.

Once we do that, I would also rename `findRepositoryRoot` to `_builder_findRepoRoot`, and rename `die` to `builder_die` (and see if we can implement color in it also).

Don't set `SHLVL` in builder.inc.sh -- it should be as pure as possible in its functionality.

At the end of the day, we'll `. "$(dirname "$THIS_SCRIPT")/../resources/builder.inc.sh"` from scripts in other repos, and one day do the same in scripts in Keyman repo, and avoid the `build/` folder (which also has problems because it's a standard build output path name...)

2022-09-27 03:56 UTC, mcdurdin commented on resources/shellHelperFunctions.sh
> +#!/usr/bin/env bash
Let's not include this file. We shouldn't need it for this environment.

2022-09-28 03:15 UTC, darcywong00 commented on build.sh
> +  composer check-docker-links
Do we want this to be consistent with the GitHub action?

https://github.com/keymanapp/help.keyman.com/blob/191fe6144d1cfbf2557761c277c420e6c4030cb3/.github/workflows/ci.yml#L94-L107

2022-09-28 03:17 UTC, darcywong00 commented on build.sh
> +REPORT_STYLE=local  # Default setting.
Maybe this can be removed?

2022-09-28 03:18 UTC, darcywong00 commented on build.sh
> +. "$REPO_ROOT/resources/shellHelperFunctions.sh"
Needed for get_builder_OS (l.54)

2022-09-28 03:19 UTC, darcywong00 commented on build.sh
> +. "$(dirname "$THIS_SCRIPT")/resources/build/builder.inc.sh"
Note: using builder.inc.sh instead of "standard" build-utils.sh

2022-09-28 03:49 UTC, darcywong00 commented on build.sh
> +  #verify_npm_setup
Is this also needed? (from cy.yml)
https://github.com/keymanapp/help.keyman.com/blob/191fe6144d1cfbf2557761c277c420e6c4030cb3/.github/workflows/ci.yml#L87-L88

2022-09-28 04:08 UTC, darcywong00 commented on resources/shellHelperFunctions.sh
> +#!/usr/bin/env bash
Needed for get_builder_OS() unless that also gets moved to builder.inc.sh
`os_id` becomes readonly?

2022-09-28 04:28 UTC, mcdurdin commented on build.sh
> +  #verify_npm_setup
* We wouldn't want tier.txt. That's only for CI testing.
* `composer install` is good (don't include `--no-progress` flag I think)
* Delete `#verify_npm_setup`

2022-09-28 04:40 UTC, mcdurdin requested changes
A few changes requested here. Certainly moving in the right direction, thanks!

2022-09-28 04:40 UTC, mcdurdin commented on .gitignore
> +resources/environment.sh
This shouldn't be needed.

2022-09-28 04:40 UTC, mcdurdin commented on Readme.md
> +On Windows, also install [WSL2](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview)
It's possible to run Docker on hyper-v as an alternative to WSL2

2022-09-28 04:40 UTC, mcdurdin commented on build.sh
> +. "$(dirname "$THIS_SCRIPT")/resources/build/builder.inc.sh"
Note, builder.inc.sh should be in /resources/, not /resources/build/

2022-09-28 04:40 UTC, mcdurdin commented on build.sh
> +. "$REPO_ROOT/resources/shellHelperFunctions.sh"
Let's avoid pulling this in. shellHelperFunctions is full of Keyman-specific stuff. It's a one liner to detect Windows:

```bash
if [[ $OSTYPE =~ msys|cygwin ]]; then
  ... windows code
fi
```

2022-09-28 04:40 UTC, mcdurdin commented on build.sh
> +REPORT_STYLE=local  # Default setting.
Yes, remove it; it comes straight out of common\web\keyboard-processor\build.sh in the Keyman repo.

2022-09-28 04:40 UTC, mcdurdin commented on build.sh
> +# END - Script parameter configuration
```suggestion
```

2022-09-28 04:40 UTC, mcdurdin commented on build.sh
> +  #verify_npm_setup
```suggestion
```

2022-09-28 04:40 UTC, mcdurdin commented on build.sh
> +  #npm run clean
```suggestion
```

2022-09-28 04:40 UTC, mcdurdin commented on build.sh
> +  composer check-docker-links
Probably a good idea. Then we can just call build.sh from ci.yml

2022-09-28 04:40 UTC, mcdurdin commented on resources/shellHelperFunctions.sh
> +#!/usr/bin/env bash
If we were to do this, we'd call it `builder_os` variable. We'd keep `os_id` in shellHelperFunctions.sh and slowly fixup existing scripts to use `builder_os`.

2022-09-28 10:37 UTC, mcdurdin requested changes
Some small tweaks, but one big thing: I'm pretty uncomfortable with the `clean` action right now ... am I reading it right?

2022-09-28 10:37 UTC, mcdurdin commented on build.sh
> +# END - Script parameter configuration
```suggestion
```

2022-09-28 10:37 UTC, mcdurdin commented on build.sh
> +builder_check_color "$@"
```suggestion
```

Not required here -- this is only needed if we use colour in the builder_describe call.

TODO: a future tweak could make this entirely internal within the builder.inc.sh script, so that we don't have to jump through this hoop for build.sh scripts: just call it at the same time as we do _builder_init (and then rename to _builder_check_color_param)

2022-09-28 10:37 UTC, mcdurdin commented on build.sh
> +  docker rmi $(docker images -q)
Isn't this dangerous? Won't it kill *all* docker containers and images, even unrelated ones? If so, that could be pretty disastrous!

2022-09-28 23:22 UTC, darcywong00 commented on build.sh
> +  docker rmi $(docker images -q)
Yeah, the clean is pretty excessive. I'll investigate if I can limit it to `keyman-websites` images.

2022-09-29 02:13 UTC, darcywong00 commented on build.sh
> +  docker rmi $(docker images -q)
k, I've updated clean to only remove `keyman-website` images. Though this may impact the local keyman.com site if it also uses the same image

2022-09-29 23:45 UTC, mcdurdin requested changes
Looking very close. Just minor action suggestions to round this out.

2022-09-29 23:45 UTC, mcdurdin commented on build.sh
>    fi
This should probably be under a `./build.sh start` action, and we could have a corresponding `stop` action (from `clean`, although probably still do the `docker container stop` in the `clean` action)?

Question if `stop` should `docker container rm` as well?

2022-09-30 01:00 UTC, darcywong00 commented on build.sh
>    fi
ok. I've added start and stop actions.

I only have the clean action rm containers and images.

2022-09-30 01:17 UTC, mcdurdin requested changes
Super close now :grin:

2022-09-30 01:17 UTC, mcdurdin commented on build.sh
> +
❤️ These are great! We can generalize when we start using across multiple sites.

I see a need for us to figure out a good way to share between repos -- this and other scripts. I think build.sh will need to do this one day in the configure step? Having some ideas, won't block this PR, but should solve both this and the common PHP files.

2022-09-30 01:17 UTC, mcdurdin commented on build.sh
> +    echo "${COLOR_RED}ERROR: Docker container doesn't exist. Run ./build.sh build first"
```suggestion
    echo "${COLOR_RED}ERROR: Docker container doesn't exist. Run ./build.sh build first${COLOR_RESET}"
```

:+1:

2022-09-30 01:17 UTC, mcdurdin commented on build.sh
> +fi
Suggest putting this before `build` action, so you can do:

`./build.sh stop build start`

and it will run the actions in the order the user expects.

Conversely, I can't see `./build.sh start stop` as a sensible thing really...

Note: I know this is a little bit unintuitive at present -- build script actions are always run in a specific order, regardless of the order in which they are specified!

2022-09-30 01:18 UTC, mcdurdin commented on Readme.md
> +#### Clean the Docker container and image
```suggestion
#### Remove the Docker container and image
```

2022-09-30 01:34 UTC, merged