Add phphelpfile.md documentation
keymanapp/help.keyman.com pull request #650
Opened 2022-11-17 02:36 UTC by DavidLRowe

A possible follow-up would be to change the developer/keyboards/_shared/organize-folder-structure.php file to include reference to the shared phphelpfile.md file.

2022-11-17 04:46 UTC, mcdurdin approved these changes

2022-11-17 05:07 UTC, mcdurdin requested changes
The link in step-0 is not correct (one too many `../`!):

```
Getting links from: http://localhost:8888/developer/keyboards/github/step-0
├─BROKEN─ http://localhost:8888/developer/_shared/phphelpfile (HTTP_404)
```

2022-11-17 19:34 UTC, DavidLRowe commented
@mcdurdin Sorry to bother you, but I'm groping in the dark trying to figure out what is wrong with the link. I've taken out the extra level, tried adding the `.md` extension (after noticing all the other files in the `_shared` folder were `.php` files). Should I forget about putting it in `_shared` and move it to the `github` folder?

2022-11-17 20:27 UTC, mcdurdin commented on developer/keyboards/github/step-0.md
> + For more information on creating the PHP help file see [Creating a PHP help file](../_shared/phphelpfile.md).
```suggestion
 For more information on creating the PHP help file see [Creating a PHP help file](../_shared/phphelpfile).
```

This should fix it. Sorry for the pain!

2022-11-17 20:30 UTC, mcdurdin commented on developer/keyboards/github/step-0.md
> + For more information on creating the PHP help file see [Creating a PHP help file](../_shared/phphelpfile.md).
I see you fixed it correctly in 4efe5f96fc6d1f41d2ccf7f01296df685e027e03, but that then added phphelpfile to the files to check, and it too has a broken link:

```
Getting links from: http://localhost:8888/developer/keyboards/_shared/phphelpfile
├─BROKEN─ http://localhost:8888/developer/keyboards/_shared/ (HTTP_403)
```

2022-11-17 20:32 UTC, mcdurdin commented on developer/keyboards/github/step-0.md
> + For more information on creating the PHP help file see [Creating a PHP help file](../_shared/phphelpfile.md).
I suggest that we move the phphelpfile.md up to /developer/keyboards/ and link it from there. The _shared folder was used to share content in .php but it's a little harder to do that with Markdown. (Every time we try to remove duplication in documentation, we end up tripping over ourselves somewhere!)

2022-11-17 22:24 UTC, DavidLRowe commented
I'll try it, but I think a previous attempt with that text failed (though I've lost track of the permutations at this point).

2022-11-17 22:27 UTC, mcdurdin commented
> I'll try it, but I think a previous attempt with that text failed (though I've lost track of the permutations at this point).

Yes, this was due to the issue with having the file in _shared. I'm happy to take over this PR, fix it up and merge if you like.

2022-11-17 23:34 UTC, DavidLRowe commented
@mcdurdin That would be great, but I'd like to know what I did wrong (which I guess I can see from the PR when it finally passes the test).

2022-11-18 00:48 UTC, mcdurdin commented
OK, I moved phphelpfile.md up a folder, as the problem was with the generated content for the _shared folder -- it doesn't have an index.md or index.php so there were problems with that.

I also tweaked the title and the included code blocks in the file to format them better.

2022-11-18 00:48 UTC, mcdurdin approved these changes

2022-11-18 02:18 UTC, mcdurdin commented
Unrelated broken links this time!

```
Getting links from: http://localhost:8888/keyboard/gff_mesobe_fidelat
├─BROKEN─ http://localhost:8888/keyboard/gff_mesobe_fidelat/1.0/gff_mesobe_fidelat-default-1.jpeg (HTTP_404)
├─BROKEN─ http://localhost:8888/keyboard/gff_mesobe_fidelat/1.0/gff_mesobe_fidelat-default-2.jpeg (HTTP_404)
├─BROKEN─ http://localhost:8888/keyboard/gff_mesobe_fidelat/1.0/gff_mesobe_fidelat-default-3.jpeg (HTTP_404)
├─BROKEN─ http://localhost:8888/keyboard/gff_mesobe_fidelat/1.0/gff_mesobe_fidelat-numerals-1.jpeg (HTTP_404)
├─BROKEN─ http://localhost:8888/keyboard/gff_mesobe_fidelat/1.0/gff_mesobe_fidelat-punctuation-1.jpeg (HTTP_404)
├─BROKEN─ http://localhost:8888/keyboard/gff_mesobe_fidelat/1.0/gff_mesobe_fidelat-punctuation-2.jpeg (HTTP_404)
├─BROKEN─ http://localhost:8888/keyboard/gff_mesobe_fidelat/1.0/gff_mesobe_fidelat-tablet-punctuation-1.jpeg (HTTP_404)
```

2022-11-18 02:19 UTC, merged

2022-11-18 02:28 UTC, dyacob commented
@mcdurdin I just noticed it also a few minutes back, the fix needed is to add "images/" to the path.  I think a width="100%" attribute is also needed here and with gff_harege_fidelat.  Can I make these changes to the php file without bumping the keyboard version numbers?

2022-11-18 05:37 UTC, mcdurdin commented
> Can I make these changes to the php files without bumping the keyboard version numbers?

Yes