Converted constraints.php to markdown
keymanapp/help.keyman.com pull request #739
Opened 2023-06-30 08:47 UTC by Meng-Heng

2023-06-30 08:57 UTC, jahorton requested changes
Looks good aside from some remaining anchors.

2023-06-30 08:57 UTC, jahorton commented on developer/language/guide/constraints.md
> +## Typical usage of constraints {#typical-usage-of-constraints}
```suggestion
## Typical usage of constraints
```

2023-06-30 08:57 UTC, jahorton commented on developer/language/guide/constraints.md
> +## Rejecting both context and keystroke {#rejecting-both-context-and-keystroke}
```suggestion
## Rejecting both context and keystroke
```

2023-06-30 08:57 UTC, jahorton commented on developer/language/guide/constraints.md
> +## Rejecting keystrokes after a context {#rejecting-keystrokes-after-a-context}
```suggestion
## Rejecting keystrokes after a context
```

2023-06-30 08:57 UTC, jahorton commented on developer/language/guide/constraints.md
> +## Rejecting keystrokes {#rejecting-keystrokes}
```suggestion
## Rejecting keystrokes
```

2023-06-30 09:07 UTC, jahorton approved these changes

2023-06-30 09:10 UTC, mcdurdin commented on developer/language/guide/constraints.md
> +    + "Q" > nul
Can we use the triple-backtick method of formatting code, rather than indents, as it allows us to select a language:
````suggestion
```keyman
+ "Q" > nul
```
````

There are several other places we'll need to do that, too.

2023-07-03 02:09 UTC, jahorton commented on developer/language/guide/constraints.md
> +    + "Q" > nul
I would like to point out that the more we focus on catching pre-existing nits like this during the process of converting pages from a PHP/HTML base to Markdown, the slower the process is going to be.  

I guess it's all fine and good when we're looking at single files, but there are hundreds, if not thousands, to be converted.  It may be wise to "pick our battles" here.

2023-07-03 02:10 UTC, jahorton commented on developer/language/guide/constraints.md
> +    + "Q" > nul
If `pandoc` has an option for configuring that, I'd love to see it.  As far as I can tell, it's fairly opinionated and doesn't let us set that.

2023-07-07 07:18 UTC, mcdurdin commented on developer/language/guide/constraints.md
> +-   [`nomatch` rule](../reference/nomatch "nomatch rule")
```suggestion
-   [`nul` statement](../reference/nul)
-   [`beep` statement](../reference/beep)
-   [`nomatch` rule](../reference/nomatch)
```

Just spotted this!

2023-07-07 07:18 UTC, Meng-Heng commented on developer/language/guide/constraints.md
> +    + "Q" > beep
````suggestion
```
+ "Q" > beep
```
````

2023-07-07 07:18 UTC, Meng-Heng commented on developer/language/guide/constraints.md
> +    "ba" + "d" > context
````suggestion
```
"ba" + "d" > context
```
````

2023-07-07 07:18 UTC, Meng-Heng commented on developer/language/guide/constraints.md
> +    "eras" + "e" > beep
````suggestion
```
"eras" + "e" > beep
```
````

2023-07-07 07:19 UTC, merged