06-July-23 Converted stores.php to stores.md. I deleted a language-keyman class in md since it was interfering with the whole page, will it be a problem in the future?
keymanapp/help.keyman.com pull request #744
Opened 2023-07-06 07:33 UTC by Meng-Heng

2023-07-07 07:17 UTC, jahorton requested changes
Apologies for all the requested changes; almost all of these will be covered by the updates I've made to the conversion tool (now hosted at https://github.com/jahorton/keyman-site-page-converter).

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +    + "Q" > nul
````suggestion
```
+ "Q" > nul
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +    + "Q" > beep
````suggestion
```
+ "Q" > beep
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +    "ba" + "d" > context
````suggestion
```
+ "ba" + "d" > context
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +    "ba" + "d" > context beep
````suggestion
```
+ "ba" + "d" > context beep
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +    "eras" + "e" > nul
````suggestion
```
+ "eras" + "e" > nul
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +    "eras" + "e" > beep
````suggestion
```
+ "eras" + "e" > beep
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +-   [`nomatch` rule](../reference/nomatch "nomatch rule")
```
-   [`nul` statement](../reference/nul)
-   [`beep` statement](../reference/beep)
-   [`nomatch` rule](../reference/nomatch)
```

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    store(storeName) storeContents
````suggestion
```
store(storeName) storeContents
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    store(vowel_keys) [K_A] [K_E] [K_I] [K_O] [K_U]
````suggestion
```
store(vowels) 'aeiouAEIOU'
store(vowels_lower) 'ae' U+0069 U+006F U+0075
store(φωνήεντα) 'αειου'
store(vowel_keys) [K_A] [K_E] [K_I] [K_O] [K_U]
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    ... + any(storeName) > ...
````suggestion
```
    any(storeName) + ... > ...
    ... + any(storeName) > ...
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    index(storeName, offset)
````suggestion
```
index(storeName, offset)
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    + any(lowercase) > index(uppercase, 1)    c translate vowels to upper case
````suggestion
```
store(lowercase) "aeiou"
store(uppercase) "AEIOU"

+ any(lowercase) > index(uppercase, 1)    c translate vowels to upper case
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    any(vowel) + '^' > index(vowel_circum, 1)
````suggestion
```
store(vowel) 'aeiouAEIOU'
store(vowel_circum) 'âêîôûÂÊÎÔÛ'
any(vowel) + '^' > index(vowel_circum, 1)
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +## Rejecting keystrokes after a context {#rejecting-keystrokes-after-a-context}
```suggestion
## Rejecting keystrokes after a context
```

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +## Rejecting both context and keystroke {#rejecting-both-context-and-keystroke}
```suggestion
## Rejecting both context and keystroke
```

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
> +## Typical usage of constraints {#typical-usage-of-constraints}
```suggestion
## Typical usage of constraints
```

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    outs(storeName)
````suggestion
```
    outs(storeName)
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +[named constants](constants "Named Constants"){.link}.
```suggestion
[named constants](constants).
```

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    + $vowel_a > $vowel_alpha
````suggestion
```
store(vowels_lower) 'aeiou'
store(vowels_upper) 'AEIOU'
store(vowels) outs(vowels_lower) outs(vowels_upper)

store(vowel_a) 'a'
store(vowel_alpha) 'α'
+ outs(vowel_a) > outs(vowel_alpha)
+ $vowel_a > $vowel_alpha
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    store(&name) "My First Keyboard"
````suggestion
```
store(&name) "My First Keyboard"
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    + any(key) > call(DLLFunction)
````suggestion
```
    store(DLLFunction) "myimx.dll:KeyEvent"
    + any(key) > call(DLLFunction)
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +    if(opt_composed = '1') any(vowel) + '^' > index(vowel_circum, 2)
````suggestion
```
store(opt_composed) '0'
store(vowel) 'aeiouAEIOU'
store(vowel_circum) 'âêîôûÂÊÎÔÛ'
     
+ [CTRL ALT K_1] > set(opt_composed='1')
+ [CTRL ALT K_0] > set(opt_composed='0')
if(opt_composed = '0') any(vowel) + '^' > index(vowel, 2) U+0302
if(opt_composed = '1') any(vowel) + '^' > index(vowel_circum, 2)
```
````

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +[`store()` statement](../reference/store "store() statement")
```suggestion
The following statements are used with stores:

[`any()` statement](../reference/any)

Matches on an array of characters

[`call()` statement](../reference/call)

Calls an Input Method Extension

[`if()` statement](../reference/if)

Tests the content of a variable store

[`index()` statement](../reference/_index)

Outputs from an array of characters

[`outs()` statement](../reference/outs)

Outputs an array of characters

[`reset()` statement](../reference/reset)

Resets the content of a variable store to the default

[`save()` statement](../reference/save)

Persists the content of a variable store

[`set()` statement](../reference/set)

Updates the content of a variable store

[`store()` statement](../reference/store)
```

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/constraints.md
Note:  this file is also changed by #739.  Make any changes there and wait for a merge first before making them here, as the changes suggested in this file should already be covered there.

2023-07-07 07:17 UTC, jahorton commented on developer/language/guide/stores.md
> +keys](virtual-keys "Virtual Keys and Virtual Character Keys").
```suggestion
Apart from characters, two other elements are allowed in stores:
[deadkeys](../reference/deadkey) and [virtual keys](virtual-keys).
```

2023-07-07 07:26 UTC, jahorton approved these changes

2023-07-07 07:28 UTC, mcdurdin commented
> I deleted a language-keyman class in md since it was interfering with the whole page, will it be a problem in the future?

If I understand you, it was something like this left in the Markdown file:

```
<pre class="language-keyman"><code>
```

Yes, it is correct to remove that -- pandoc should have removed that automatically!

2023-07-07 07:28 UTC, merged

2023-07-07 13:55 UTC, darcywong00 commented
This is merged into staging. I see the CI link checker on other PR's are also flagging references to `stores.php` (should change to `stores`)
* /developer/language/guide/headers.md
* /developer/language/reference/_index.php

2023-07-10 01:47 UTC, jahorton commented
> This is merged into staging. I see the CI link checker on other PR's are also flagging references to `stores.php` (should change to `stores`)
> 
>     * /developer/language/guide/headers.md
> 
>     * /developer/language/reference/_index.php

Did you figure out which files were the issue manually?  Or is that available somewhere buried within the link-checker report?  All I see is stuff _implying_ that the visited page is a 404-page, but not even _that_... explicitly, at least.

2023-07-10 01:57 UTC, darcywong00 commented
Sorry the link checker didn't show anything helpful, so I just locally searched my folder for the php files