Model to md
keymanapp/help.keyman.com pull request #750
Opened 2023-07-14 06:20 UTC by soysreyvy

2023-07-14 06:32 UTC, jahorton commented on developer/lexical-models/submission/index.php
This file should be deleted, now that we're replacing it.

2023-07-28 23:23 UTC, darcywong00 requested changes
With the pending changes from #766, we'll want to remove `.php` from the 5 links

2023-07-31 01:23 UTC, jahorton commented
> With the pending changes from #766, we'll want to remove `.php` from the 5 links

That's the point of #766.  Rather than try to get the interns to update 20-odd PRs to resolve conflicts caused by merging it... I'll be merging these and then merge the result into #766; it's way easier to resolve things in one place, and the expected conflicts are all deleted files, which are notably easy to resolve in this case.

2023-07-31 01:24 UTC, jahorton approved these changes

2023-07-31 01:25 UTC, merged