Kl page
keymanapp/help.keyman.com pull request #793
Opened 2023-08-04 07:21 UTC by kimleangkheng

2023-08-04 07:37 UTC, Nnyny requested changes

2023-08-04 07:37 UTC, Nnyny commented on developer/language/reference/ethnologuecode.md
> +[www.ethnologue.com](http://www.ethnologue.com/){.ulink
```suggestion
[www.ethnologue.com](http://www.ethnologue.com/)
```

2023-08-04 07:37 UTC, Nnyny commented on developer/language/reference/ethnologuecode.md
> +target="_blank"}.
```suggestion
.
```

2023-08-04 07:37 UTC, Nnyny commented on developer/language/reference/includecodes.md
> +[named character constants](../guide/constants){.link}. Keyman Developer
```suggestion
[named character constants](../guide/constants). Keyman Developer
```

2023-08-04 07:50 UTC, jahorton commented on developer/language/reference/ethnologuecode.md
> +target="_blank"}.
Good catch!  The `target="_blank"` would admittedly be nice to keep... if it worked.  

I just tested adding that in to a different link on my machine... alas, I don't think we can use that feature.  So, good catch; we do need to remove both parts within the `{` and `}`.

2023-08-10 02:11 UTC, jahorton approved these changes

2023-08-10 02:11 UTC, merged