docs:  Add TSF knowledge base page
keymanapp/help.keyman.com pull request #833
Opened 2023-10-17 23:42 UTC by rc-swag

Fixes:832

2023-10-17 23:44 UTC, rc-swag commented on knowledge-base/kb0110.md
> +Certain Linux and MacOS applications also have the ability to read the current 'context' from applications.
What about iOS In android and iOS are is the ability to read the current context always available?

2023-10-18 01:32 UTC, mcdurdin requested changes

2023-10-18 01:32 UTC, mcdurdin commented on knowledge-base/kb0110.md
> +The Text Services Framework, or TSF, is a set of components for modern applications that support advanced input and text processing. It
Can you format this document to our standard line length of 80 chars for .md? I often use Rewrap extension (Alt+Q wraps, Alt+Shift+Q unwraps) on VSCode for this.

2023-10-18 01:32 UTC, mcdurdin commented on knowledge-base/kb0110.md
> +This includes: MS Office Applications, Firefox, Adobe Create Cloud Apps and Notepad in Windows 11
The list is a bit longer than this!

```suggestion
For example, this includes: MS Office Applications, Firefox, Adobe Create Cloud Apps, Wordpad, SIL Fieldworks, and Notepad in Windows 11.
```

2023-10-18 01:32 UTC, mcdurdin commented on knowledge-base/kb0110.md
> +Certain Linux and MacOS applications also have the ability to read the current 'context' from applications.
All apps on iOS and Android can read the context. Similarly, on web, context is always available.

2023-10-19 03:45 UTC, rc-swag commented on knowledge-base/kb0110.md
> +Certain Linux and MacOS applications also have the ability to read the current 'context' from applications.
> All apps on iOS and Android can read the context. Similarly, on web, context is always available.

I thought that maybe the case I am going to add your reply to the document.

2023-10-19 03:47 UTC, rc-swag commented on knowledge-base/kb0110.md
> +This includes: MS Office Applications, Firefox, Adobe Create Cloud Apps and Notepad in Windows 11
I will remove `this includes`, as for example makes it redundant.

2023-10-19 04:01 UTC, mcdurdin approved these changes

2023-10-19 04:48 UTC, rc-swag commented
@darcywong00 or @mcdurdin  This CI / build-test is failing and when I check the link the image complained about is missing. Should I raise an Issue or is this working already over on staging?

2023-10-19 04:48 UTC, merged

2023-10-19 05:32 UTC, mcdurdin commented
> This CI / build-test is failing and when I check the link the image complained about is missing. Should I raise an Issue or is this working already over on staging?

Already an issue open at keymanapp/keyboards#2412