Changing the link in /developer/engine/android/16.0 "See also" section
keymanapp/help.keyman.com pull request #927
Opened 2023-12-26 08:57 UTC by Meng-Heng

The link was pointed to 14.0 but titled as 15.0

2024-01-02 15:09 UTC, mcdurdin approved these changes

2024-01-02 15:09 UTC, mcdurdin requested changes
Sorry, I missed this the first time through. Not sure why kb0033.md is deleted, but we'll need to restore it for this PR

2024-01-04 05:46 UTC, Meng-Heng commented
> Sorry, I missed this the first time through. Not sure why kb0033.md is deleted, but we'll need to restore it for this PR

Sorry, @mcdurdin. I don't know that the file is needed because it was in a commit and was pushed already. 
Thank you for telling me. I think I got it recovered now.

2024-01-05 04:04 UTC, mcdurdin approved these changes
Good work, looks fine now. Thanks for your attention to detail!

2024-01-08 04:11 UTC, merged