fix: changing a link in /developer/keyboards/advanced/step-5
keymanapp/help.keyman.com pull request #928
Opened 2023-12-26 09:28 UTC by Meng-Heng

changing the link title 'Organizing the keyboard files' 
changing the step number according to the link title.

> Following the file layout documented in [Organizing the Keyboard
> Files](step-4), your keyboard layout should be in a folder similar

2024-01-02 15:11 UTC, mcdurdin requested changes
Thanks for the PR @Meng-Heng. Once you restore those two files which are not part of the fix, I can merge this PR

2024-01-02 15:11 UTC, mcdurdin commented on developer/engine/android/16.0/index.php
This file needs to be restored

2024-01-02 15:11 UTC, mcdurdin commented on knowledge-base/kb0033.md
This file also needs to be restored

2024-01-03 08:54 UTC, Meng-Heng commented on knowledge-base/kb0033.md
I got the files restored but I got an issue while trying to push to my origin

> fatal: unable to access 'https://github.com/Meng-Heng/help.keyman.com.git/': Could not resolve host: github.com

I will tackle this tomorrow

2024-01-19 07:59 UTC, mcdurdin approved these changes

2024-01-19 08:00 UTC, mcdurdin commented on developer/engine/android/16.0/index.php
> +  <li><a href="/developer/engine/android/14.0/" title="Keyman Engine for Android 15.0">Keyman Engine for Android 15.0</a></li>
```suggestion
  <li><a href="/developer/engine/android/15.0/" title="Keyman Engine for Android 15.0">Keyman Engine for Android 15.0</a></li>
```

2024-01-19 08:00 UTC, mcdurdin approved these changes

2024-01-19 08:01 UTC, merged