converted to md in developer/16.0/guides/develop/touch-keyboard…
keymanapp/help.keyman.com pull request #934
Opened 2024-01-05 03:21 UTC by Meng-Heng

There are two files in the folder that were PHP files so I went ahead and converted it to markdown. If there is anything I need to change, I will be happy to do so.

For reference - https://help.keyman.com/developer/16.0/guides/develop/touch-keyboard-tutorial/

This section is now changed to a table
> |             |          |     |          |     |     |          |     |          |
> |-------------|----------|-----|----------|-----|-----|----------|-----|----------|
> | `        ɓ` | `U+0253` | `Ɓ` | `U+0181` |     | `ɗ` | `U+0257` | `Ɗ` | `U+018A` |
> | `        ŋ` | `U+014B` | `Ŋ` | `U+014A` |     | `ƴ` | `U+01B4` | `Ƴ` | `U+01B3` |

I cannot find anything that can reimplement the box `<kbd>` so this is the closest thing I found

> ```
> ago) used the ```/``` key as the deadkey.
> ***`/`*** ***`b`*** gave ɓ,
> ***`/`*** ***`d`*** gave ɗ, and so on.
> ```

2024-01-05 03:45 UTC, mcdurdin commented
Looks good so far!

> This section is now changed to a table

:+1:

> I cannot find anything that can reimplement the box `<kbd>` so this is the closest thing I found

You can actually continue to use `<kbd>x</kbd>` in the Markdown content. So do go ahead and update to use that tag :grin:

2024-01-05 03:47 UTC, mcdurdin requested changes

2024-01-05 03:47 UTC, mcdurdin commented on developer/16.0/guides/develop/touch-keyboard-tutorial/index.md
> +| `        ŋ` | `U+014B` | `Ŋ` | `U+014A` |     | `ƴ` | `U+01B4` | `Ƴ` | `U+01B3` |
```suggestion
|     |          |     |          |     |     |          |     |          |
|-----|----------|-----|----------|-----|-----|----------|-----|----------|
| `ɓ` | `U+0253` | `Ɓ` | `U+0181` |     | `ɗ` | `U+0257` | `Ɗ` | `U+018A` |
| `ŋ` | `U+014B` | `Ŋ` | `U+014A` |     | `ƴ` | `U+01B4` | `Ƴ` | `U+01B3` |
```

2024-01-05 03:47 UTC, mcdurdin commented on developer/16.0/guides/develop/touch-keyboard-tutorial/index.md
> +ago) used the ```/``` key as the deadkey.
```suggestion
ago) used the <kbd>/</kbd> key as the deadkey.
```

And others in the same way. `<kbd>` is a valid tag to use in Markdown

2024-01-05 05:12 UTC, Meng-Heng commented
> You can actually continue to use <kbd>x</kbd> in the Markdown content. So do go ahead and update to use that tag 😁

Now, it has changed. I was going to keep <kbd> but thinking it was a tag so I removed it 😅

2024-01-19 08:01 UTC, mcdurdin approved these changes

2024-01-19 08:01 UTC, merged