docs: Updating touch keyboard tutorial for Keyman 16
keymanapp/help.keyman.com pull request #987
Opened 2024-02-06 20:10 UTC by sewhite

The touch interface is better in Keyman 16. The tutorial on developing a simple touch keyboard needs updating to show the new interface. I've edited the making-touch-keyboard.php and added some different screenshots.

2024-02-07 01:45 UTC, mcdurdin commented
Thank you for the contribution -- I'll review these as part of our updates to Keyman Developer 17 UI screenshots and incorporate your changes there.

2024-02-07 01:46 UTC, mcdurdin commented
> I've edited the making-touch-keyboard.php

I note that this file has not been updated here?

2024-02-07 14:14 UTC, sewhite commented
It  is now updated on my fork. (It needed another edit anyway). Do I need to redo the pull request?

2024-02-07 20:10 UTC, sewhite commented
I see the build test reports this error:

> Getting links from: http://localhost:8888/developer/current-version/guides/develop/touch-keyboard-tutorial/making-touch-keyboard
> ├─BROKEN─ http://localhost:8888/cdn/dev/img/developer/100/simpleTouchKeyboard_12-2.png (HTTP_404)

I don't see what the problem is. That image file is in my fork.

2024-02-07 23:22 UTC, mcdurdin commented
> I don't see what the problem is. That image file is in my fork.

I see you've resolved this

2024-02-07 23:23 UTC, mcdurdin commented
> Do I need to redo the pull request?

No, you've added the file here, I can see that.

I will review next week when I am working on the Developer documentation -- trying to move to beta this week

2024-02-16 01:38 UTC, darcywong00 commented
hi @sewhite - We've recently revamped our Keyman websites to use Apache instead of IIS. For notes on configuring this locally, refer to 
https://github.com/keymanapp/keyman/blob/master/docs/websites/README.md

You'll probably need to rebase your fork on the latest master to get all the updates.

2024-02-17 00:36 UTC, darcywong00 commented
> I've looked at the readme about moving to Apache. I don't think that move affects this request to update a tutorial, is that right?

Right. It's just FYI in case you want to preview what your changes (or future PRs) would look like on the website

2024-03-21 07:18 UTC, mcdurdin requested changes
I've now had a chance to go through this. Unfortunately, it coincides with a rewrite of the .php to .md so I am going to suggest that we close this and re-open as a new PR.

I have gone through the .md 17.0 version and rewritten it to incorporate most of your changes; you should be able to take this and apply it to a new PR:

````
---
title: Making a touchscreen keyboard
---

## Setting up your Keyman project

This is a useful convention for keeping track of your files:

1.  Create a folder on your hard drive for all your Keyman developer
    files
2.  In that folder, create a folder for this project, named after the
    language. Use all lowercase letters for compatibility with other
    platforms.
3.  Now create a project in Keyman Developer with the same name as the
    new folder, and save it inside the new folder

Now you will be able to use this project to organize and create any
files for desktop, mobile, web or other. It also facilitates uploading
the files to the Keyman website later on.

## Add touch to an existing keyboard or create a new keyboard?

You can add a mobile touchscreen keyboard to an existing desktop
keyboard, or you can create a new touchscreen keyboard from scratch. You
should be aware that there will be cross-over between mobile and desktop
keyboards. (In Keyman terms, "desktop" includes laptop computers or any
device with a physical keyboard). Your mobile device can have an
external keyboard, which will use the desktop Keyman keyboard. So the
Keyman strategy is to always bundle touch keyboards with desktop
keyboards to make them work on multiple platforms.

If creating from scratch, you click the New icon in the Keyman Developer
toolbar (or select File &gt; New from the menu), and specify the file
name for your keyboard. We recommend a name using only lowercase
letters, numbers and underscore. I’ll choose “mobile_fulfulde.kmn” .

![choose new file
type](/cdn/dev/img/developer/100/simpleTouchKeyboard_1.png)

## Adding the required metadata

After creating the file, Keyman Developer will ask you to name the
keyboard. This name can include spaces and upper case letters if
desired. I’ll name this one “Fulfulde for Mobile”.

![keyboard
metadata](/cdn/dev/img/developer/100/simpleTouchKeyboard_2.png)

The first thing you need to do is to tell Keyman Developer this keyboard
will include some kind of mobile device.  You do this in the Targets
list just below the keyboard name. I’ll select “mobile ” in the list,
(towards the end). You see in the picture above that Keyman Developer
checked the “windows” box by default, I can uncheck that or leave it
checked if I am going to add a Windows keyboard to this set.

![mobile target](/cdn/dev/img/developer/100/simpleTouchKeyboard_3.png )

This will include all mobile devices, both Android and iOS, both phones
and tablets. It is possible if needed to select Android only or iOS only
if needed, and to develop a different keyboard layout for tablets than
for phones, but for this example, with only a few characters needed to
be added to the default keyboards, there is no need for that kind of
complexity.

(If you are adding a mobile layout to an existing keyboard file, you
would open that file in Keyman Developer, go to the Targets box and
check “mobile” or whatever mobile targets you wanted to specify, then
follow along from here).

## Adding the touch optimized feature

The next step is to add the touch-optimised feature to our keyboard
setup. If you scroll to the bottom of the details tab, there is the list
of features to add. I’ll click the Add button and choose “touch
optimised keyboard.”

![touch-optimised](/cdn/dev/img/developer/100/simpleTouchKeyboard_4.png)

Keyman developer asks me to choose one of three templates for the mobile
layout.

![three templates](/cdn/dev/img/developer/100/simpleTouchKeyboard_5.png)

The “template-latin” layout includes many accented characters, like the
default keyboards for Android and iOS do. The “template-basic” layout
has no extra characters, and the template-traditional has a few extra
characters (mostly punctuation symbols if you long-press period or full
stop). For this example, I’ll choose “template-basic” because accented
characters are not needed for Fulfulde. But if I knew that many eventual
users might want to be able to type French or other European languages
as well as Fulfulde, and wouldn’t like to have to switch the keyboard to
do so, I could choose “template-latin”.

## Defining one or several touch layouts

I select the template and click OK. Keyman Developer now adds a new tab
in the left column, the Touch Layout tab.

![touch layout](/cdn/dev/img/developer/100/simpleTouchKeyboard_6.png)

That is where we need to go now to add characters to our touch layout.
But before doing that, there is one important thing to take note of in
the touch layout. By default, Keyman Developer has created a layout for
phones and another layout for tablets. They all start out the same, but
as I add characters, I will have to make sure I add all the characters
to both layouts, or I’ll discover that my keyboard does not work for all
device sizes.

In the image, you see in the Platform box that Keyman Developer is currently showing the
tablet layout. This box is where I’d choose which layout I’d design in.

But I’m going to make this keyboard simple, and just have one layout for
both tablets and phones. So in the platform box, I am going to click
the “minus” button, to delete the tablet layout. When there is only one
mobile layout, Keyman Developer will compile that layout for all mobile
devices. (I could also have chosen to delete the phone layout and done
my layout design in the tablet layout).

![platform list](/cdn/dev/img/developer/100/simpleTouchKeyboard_7.png)

## Adding longpress characters

Now I can start adding characters. I’ll click on the “y” key in the
layout, then I’ll look at the “longpress keys” area at the lower
left.

![add longpress](/cdn/dev/img/developer/100/simpleTouchKeyboard_8.png)

I click that, and Keyman Developer adds a new key below the keyboard
layout.

![longpress added](/cdn/dev/img/developer/100/simpleTouchKeyboard_9.png)

I'm going to use this key for the y with hook. I click inside it to make it active, then I’ll go look for my y
with hook character in the character map to the right. If I type “y
hook” in the search box, Keyman Developer shows the character I’m
looking for.

![adding keycap](/cdn/dev/img/developer/100/simpleTouchKeyboard_10.png)

If I double click on the lower case y with hook, that copies the character
to the keycap box of my new key. (I could also click and drag the character from the character map to the key).

![keycap added](/cdn/dev/img/developer/100/simpleTouchKeyboard_11.png)

## New key info

There are several important pieces of information that got copied over. If we
look at the properties of the new key to the right, we see that this new key has
the “text” ƴ (what appears on the keycap), the “Unicode value” U+01B4 and the
“ID” U_01B4. All of these were copied from the character map.

NOTE: If you copy one character from the character map to a new key, then
realize you copied the wrong character, dragging a second character may not
replace all the needed information into the key. If a key has a character in it
already, it works better to hold <kbd>Ctrl</kbd> as you drag the new character
into it.

I could add the other three characters; hook b, hook d, and eng, as longpress
characters as well. I could  select the regular letter I want to longpress,
click plus in the longpress keys area and copy the needed character. Here for
example is the b with hook:

![keycap added](/cdn/dev/img/developer/100/simpleTouchKeyboard_12.png)

After I have added my four lowercase characters as longpress keys, the keyboard
looks like this.  Even when I don't have that letter selected, I can see which
keys have longpress keys by the dot beside the letter.

![keycap added](/cdn/dev/img/developer/100/simpleTouchKeyboard_1 [...]

2024-03-21 07:18 UTC, mcdurdin commented on developer/16.0/guides/develop/touch-keyboard-tutorial/making-touch-keyboard.php
> -<p>(If
I'm not sure why you've deleted this content?

2024-03-21 07:18 UTC, mcdurdin commented on developer/16.0/guides/develop/touch-keyboard-tutorial/making-touch-keyboard.php
> -<p>If
I'm not sure why you've deleted this content also?

2024-03-21 07:18 UTC, mcdurdin commented on cdn/dev/img/developer/100/simpleTouchKeyboard_10.png
These images need to go into cdn/dev/img/developer/160/, not replace the existing images which belong to an older version of the documentation.

2024-05-11 05:03 UTC, mcdurdin commented
@Meng-Heng or @Nnyny, this has been stalled for a while; could one of you take this on and apply the changes to the Markdown file in a new pull request? Thanks!

2024-05-13 04:30 UTC, Nnyny commented
@mcdurdin, I'll work on it.

2024-06-09 02:15 UTC, closed without merging