docs(linux): Update screenshots and FAQ
keymanapp/help.keyman.com pull request #995
Opened 2024-02-09 15:37 UTC by ermshiperete

Fixes #982

2024-02-11 22:25 UTC, mcdurdin approved these changes

2024-02-12 02:43 UTC, darcywong00 requested changes
I think these changes get done in the main repo and then CI syncs it to the help.keyman repo

https://github.com/keymanapp/keyman/tree/master/linux/help

2024-02-12 04:06 UTC, mcdurdin commented
> I think these changes get done in the main repo and then CI syncs it to the help.keyman repo

Good catch @darcywong00!

2024-02-19 15:48 UTC, ermshiperete commented
Replaced by https://github.com/keymanapp/keyman/pull/10768

2024-02-19 15:48 UTC, closed without merging